```{r, echo=FALSE}
suppressPackageStartupMessages(library('knitr')) 
options(width = 100)
```

---
title: "Prediction Assignment: Human Activity Recognition in Weight Lifting Exercises"
author: "Jeremy Shantz"
date: '2015-02-07'
output: html_document
---

 | Your submission should consist of a link to a Github repo with your R markdown and compiled HTML file describing your analysis. 
 | It will make it easier for the graders if you submit a repo with a gh-pages branch so the HTML page can be viewed online 
 
# Synopsis
goal: predict the manner in which they did the exercise. 
This is the "classe" variable in the training set. You may use any of the other variables to predict with. 
Please constrain the text of the writeup to < 2000 words and the number of figures to be less than 5.

Using devices such as Jawbone Up, Nike FuelBand, and Fitbit it is now possible to collect a large amount of data about personal activity relatively inexpensively. These type of devices are part of the quantified self movement – a group of enthusiasts who take measurements about themselves regularly to improve their health, to find patterns in their behavior, or because they are tech geeks. One thing that people regularly do is quantify how much of a particular activity they do, but they rarely quantify how well they do it. In this project, your goal will be to use data from accelerometers on the belt, forearm, arm, and dumbell of 6 participants. They were asked to perform barbell lifts correctly and incorrectly in 5 different ways. More information is available from the website here: http://groupware.les.inf.puc-rio.br/har (see the section on the Weight Lifting Exercise Dataset). 


# how you built your model, 
Does the submission build a machine learning algorithm to predict activity quality from activity monitors?

# Cross validation 
how you used cross validation, 
what you think the expected out of sample error is
why you made the choices you did. 
 

# Expected out of sample error
Do the authors describe what they expect the out of sample error to be and estimate the error appropriately with cross-validation?

# Estimating the error cross-validation
Do the authors describe what they expect the out of sample error to be and estimate the error appropriately with cross-validation?

# Test Cases 
2. You should also apply your machine learning algorithm to the 20 test cases available in the test data above. Please submit your predictions in appropriate format to the programming assignment for automated grading. See the programming assignment for additional details. 
You will also use your prediction model to predict 20 different test cases. 

# Citation

Velloso, E.; Bulling, A.; Gellersen, H.; Ugulino, W.; Fuks, H. [Qualitative Activity Recognition of Weight Lifting Exercises](http://groupware.les.inf.puc-rio.br/work.jsf?p1=11201). Proceedings of 4th International Conference in Cooperation with SIGCHI (Augmented Human '13) . Stuttgart, Germany: ACM SIGCHI, 2013. 
